### PR TITLE
fix: allow curl of PR metadata

### PR DESCRIPTION
**Pull request by virtuoushub**
see: https://github.com/nostalgic-css/NES.css/pull/425#issuecomment-637531225

### CODE REVIEW

**Review by SecretBase — APPROVED** [review]

**Comment by SecretBase** [comment]
Let's try it and see do it work. Will release a new image

**Comment by virtuoushub** [comment]
Cool, sorry if it is stepping on your toes; 

I published/tested it w/ an image I pushed and it seemed to work: https://app.circleci.com/pipelines/github/virtuoushub/NES.css/57/workflows/c23b4991-33dc-4803-a5a6-ab6627194a1b/jobs/461/steps

https://github.com/virtuoushub/circleci-commitlint-step/tree/tromantic
https://hub.docker.com/r/tromantic/circleci-commitlint

**Comment by SecretBase** [comment]
> Cool, sorry if it is stepping on your toes;

No. It is fine. Thank you so much for your work

**Comment by virtuoushub** [comment]
Just tested w/ your image and it worked, thank you too!

https://app.circleci.com/pipelines/github/virtuoushub/NES.css/58/workflows/901e962c-9706-44c6-aeff-911faf58fc81/jobs/471/steps

**Pull request merged**
